"""empty message

Revision ID: cd7ea7a83062
Revises: d0c7b8e4b57c
Create Date: 2025-05-05 19:16:18.142099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7ea7a83062'
down_revision = 'd0c7b8e4b57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('pixels_red', sa.Integer(), nullable=False),
    sa.Column('pixels_green', sa.Integer(), nullable=False),
    sa.Column('pixels_blue', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_record')
    # ### end Alembic commands ###
