"""empty message

Revision ID: de3c6dbcdd0a
Revises: bbc1a99e5117
Create Date: 2025-05-06 15:08:33.813356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3c6dbcdd0a'
down_revision = 'bbc1a99e5117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrada', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('salida', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_record', schema=None) as batch_op:
        batch_op.drop_column('salida')
        batch_op.drop_column('entrada')

    # ### end Alembic commands ###
